name: (Re)initialize Deployment
run-name: (Re)initialize Deployment by ${{ github.actor }}

on:
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  VENV: "venv"

jobs:
  clean-up-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Existing Folder
        uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf ${{ env.REPO_NAME }} && mkdir ${{ env.REPO_NAME }}
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: "-tt"
  
  deploy-via-sftp:
    needs: [clean-up-folder]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.VPS_USER }}
          server: ${{ secrets.VPS_IP }}
          port: ${{secrets.PORT}}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # clones entire github repo
          local_path: ./*
          # destination of the code on the server
          remote_path: ./${{ env.REPO_NAME }}
          sftpargs: '-o ConnectTimeout=15'

  install-requirements:
    needs: [deploy-via-sftp]
    runs-on: ubuntu-latest
    steps:
      - name: Remove Existing Folder
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ env.REPO_NAME }}
            apt install python3.12-venv
            python3 -m venv ${{env.VENV}}
            source ${{env.VENV}}/bin/activate
            pip install --upgrade pip
            pip install -U -r ./requirements.txt
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: "-tt"

  add-secret-variables:
    needs: [deploy-via-sftp]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - id: add-secret-variables
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ env.REPO_NAME }}
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo $?
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
  
  create-systemctl-service:
    needs: [add-secret-variables, install-requirements]
    runs-on: ubuntu-latest
    steps:
      - id: creating-systemctl-service
        uses: fifsky/ssh-action@master
        with:
          # Make sure ExecStart=, WorkingDirectory= and chmod +x point to the same directory. These may be unique to your code setup
          command: |
            sudo bash -c 'echo "[Unit]
            Description=${{ env.REPO_NAME }} Discord Bot
            After=multi-user.target
            [Service]
            Type=simple
            ExecStart=$(pwd)/${{env.REPO_NAME}}/${{env.VENV}}/bin/python3 $(pwd)/${{ env.REPO_NAME }}/launcher.py
            User=${{ secrets.VPS_USER }}
            Restart=on-failure
            RestartSec=30
            WorkingDirectory=$(pwd)/${{ env.REPO_NAME }}/
            [Install]
            WantedBy=multi-user.target" > /etc/systemd/system/${{ env.REPO_NAME }}.service'
            chmod +x $(pwd)/${{ env.REPO_NAME }}/launcher.py
            sudo systemctl enable ${{ env.REPO_NAME }}.service
            sudo systemctl daemon-reload
            sudo systemctl start ${{ env.REPO_NAME }}.service
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
    
  create-systemctl-restart:
    needs: [create-systemctl-service]
    runs-on: ubuntu-latest
    steps:
      - id: create-systemctl-restart-service
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo bash -c 'echo "[Unit]
            Description=${{ env.REPO_NAME }} Discord Bot restart
            After=multi-user.target
            [Service]
            Type=oneshot
            ExecStart=/usr/bin/systemctl restart ${{ env.REPO_NAME }}.service
            [Install]
            WantedBy=multi-user.target" > /etc/systemd/system/${{ env.REPO_NAME }}-watcher.service'
            sudo systemctl enable ${{ env.REPO_NAME }}-watcher.service
            sudo systemctl daemon-reload
            sudo systemctl start ${{ env.REPO_NAME }}-watcher.service
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}