name: Update Bot

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.VPS_USER }}
          server: ${{ secrets.VPS_IP }}
          port: ${{secrets.PORT}}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ./*
          remote_path: ./${{ env.REPO_NAME }}/
          sftpargs: '-o ConnectTimeout=15'

  restart-bot:
    needs: [deploy-via-sftp]
    runs-on: ubuntu-latest
    steps:
      - id: creating-systemctl-service
        uses: fifsky/ssh-action@master
        with:
          command: sudo systemctl start ${{ env.REPO_NAME }}-watcher.service
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}